name: Trigger Post Publisher
on:
    schedule:
        - cron: '*/5 * * * *'
    
    workflow_dispatch:

jobs:
    trigger-render-job:
        runs-on: ubuntu-latest
        steps:
            - name: Call Render Cron Job endpoint
              
              run: |
                curl -X POST \
                    -H "Authorization: Bearer ${{secrets.CRON_SECRET}}" \
                    --fail \
                    "${{ secrets.RENDER_APP_URL}}"